django-tutorial/polls/urls.py
from django.urls import path, re_path, register_converter, include
from django.contrib.auth import views as auth_views

from . import views
from . import converters

# Register any Custom Path Converters for use in urlpatterns
#register_converter(converters.FourDigitYearConverter, 'yyyy')
register_converter(converters.TwoToFourDigitYearConverter, 'yyyy')

# Specify the app namespace for reverse resolution of urls
app_name = 'polls'

# for a specific app, route host:port/appname/<pattern>
# to the appropriate handlers in the apps view module
urlpatterns_examples = [

    #path('', views.index, name='index'),
    path('2011/', views.index),
    #path('<int:year>/', views.index),   # anything int() can cast
    path('<int:year>/<int:month>/', views.index),
    path('<int:year>/<int:month>/<slug:slug>/', views.index),
    path('<int:year>/<int:month>/<slug:slug>/<uuid:user>', views.index),
    path('<int:year>/<int:month>/<slug:slug>/<uuid:user_id>/<path:path>', views.index),
    re_path(r'^toc/$', views.index),
    re_path(r'^bio/(?P<username>\w+)/$', views.index),
    path('<yyyy:yyyy>/', views.index),    # to kwargs
    #re_path(r'([0-9]+)/', views.index),  # to args

    # http://127.0.0.1:8000/polls/index/2020/hello/__Init0-9__/rest/of/it/?name=steve&age=25&age=45
    # django.http.HttpRequest(<WSGIRequest:
    #  GET '/polls/index/2020/hello/__Init0-9__/path/?name=steve&age=45'>,
    #  args: ()
    #  kwargs: {'int_key':2020, 'str_key':'hello', 'slug_key':'__Init0-9__', 'path_key':'path/'})
    #  request.GET: <QueryDict: {'name': ['steve'], 'age': ['45']}>
    # djgango.http.HttpResponse()
    # [25/Nov/2020 05:35:46]
    #  "GET /polls/index/2020/hello/__Init0-9__/path/?name=steve&age=45 HTTP/1.1" 200 40
    #  responded to above HttpRequest with status code 200 (2xx are success codes 200=OK)
    path('index/<int:int_key>/<str:str_key>/<slug:slug_key>/<path:path_key>', views.index),
]


# Generic Class Based Views
# Use <pk> for the render instance argument by default
# as you do not need to call it with class based view
# since they do it for you, provided you adhere to the
# conventional setup.
urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),  # requires id
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('pdf/', views.PdfListView.as_view(), name='pdf-list'),
    path('pdf/<int:pk>/', views.PdfDetailView.as_view(), name='pdf-detail'),
    path('pdf/<slug:slug>/', views.render_pdf_view,
         kwargs={'from': 'url_patterns'}, name='pdf-test'),


]

django-tutorial/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question_pdf = models.FileField(upload_to='pdf', default='',
                                    null=True, blank=True)
    question_img = models.ImageField(upload_to='img', default='/img/me.jpg',
                                     null=True, blank=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        # fails test
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

        now = timezone.now()
        return now - datetime.timedelta(days=1) < self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django-tutorial/polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %} Polls|Detail {% endblock %}

{% block content %}

{% if user.is_authenticated %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- in addition, create a further correspondence by
     preparing a form for the client to fill in and
     POST back. ie answer a question from the server
-->

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br>
<input type="submit" value="Vote">
</form>

{% endif %}

{% endblock %}

django-tutorial/polls/templates/polls/detail_bootstrap.html
{% extends 'base_bootstrap.html' %}

{% block title %} Polls|Detail {% endblock %}

{% block content %}

{% if user.is_authenticated %}

<h1>{{ question.question_text }}</h1>

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br>
<input type="submit" value="Vote">
</form>

{% endif %}

{% endblock %}

django-tutorial/polls/templates/polls/home.html
{% extends 'base.html' %}

{% block title %} Polls|Home {% endblock %}

{% block content %}

{% if user.is_authenticated %}

<h1> Welcome to the Polls WebApp, {{user}} </h1>

<h2> The Poll Questions are: </h2>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    {# rather than hard code a url, do a reverse lookup in the URLconf by name #}
    {#<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{# Simple Pagination interface #}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

django-tutorial/polls/templates/polls/home_bootstrap.html
{% extends 'base_bootstrap.html' %}

{% block title %} Polls|Home {% endblock %}

{% block content %}

{% if user.is_authenticated %}

<h1> Welcome to the Polls WebApp, {{user}} </h1>

<h2> The Poll Questions are: </h2>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    {# rather than hard code a url, do a reverse lookup in the URLconf by name #}
    {#<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{# Bootstrap Pagination interface #}
{% if page_obj.has_other_pages %}
  <ul class="pagination">
    <li class="page-item">
        <a class="page-link" href="?page=1">First</a>
    </li>
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}

    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active">
            <span>{{ i }} <span class="sr-only">(current)</span></span>
        </li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    </li>
  </ul>
{% endif %}

{% endif %}
{% endblock %}

django-tutorial/polls/templates/polls/pdf_detail.html
{% extends 'base.html' %}

{% block style %}{% endblock %}
{% block title %} PDF|Detail {% endblock %}
{% block authenticated %}{% endblock %}

{% block content %}

<table>
<tr><td>
{% if format == 'html' %}
  {% if question.question_img %}
    <img src="{{question.question_img.url}}" height="100px">
  {% else %}
    {%load static %}<code>PLACEHOLDER</code>
    <br> <img src="{%static 'img/me.jpg' %}" height="100px">
  {% endif %}
{% else %}
<img src="{{question.question_img.path}}" height="100px">
{% endif %}
</td><td style="vertical-align:bottom">
{% if question.question_img %}
{{question.question_img}}<br>
{{question.question_img.url}}<br>
{{question.question_img.path}}<br>
{% endif %}
</td></tr>
</table>
<hr>

<h1>{{ question.question_text }}</h1>
<hr>

<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} ?</li>
{% empty %}
Sorry, no answers to this question have been recorded.
{% endfor %}
</ul>

<hr>


{% if format == 'html' %}
<br><br>
<a href="{% url 'polls:pdf-list' %}">< Back To Pdf List</a>
{% endif %}

{% endblock %}

django-tutorial/polls/templates/polls/pdf_list.html
{% extends 'base.html' %}

{% block title %}PDF|List{% endblock title %}
{% block authenticated %}{% endblock authenticated %}
{% block style %} <style>.bg { background-color: #FF4140; }</style>{% endblock style %}

{% block content %}
<table style="border:2px solid black;" cellpadding="2">
<caption> Question List </caption>
{% for obj in object_list %}
<tr>
  <td>{{ forloop.counter }}</td>
  <td>{{ obj.question_text }}</td>
  <td>
      <a href="{% url 'polls:pdf-detail' obj.id %}"><button>pdf</button></a>
  <td>
    <div class="bg">
      <a href="{% url 'polls:pdf-detail' obj.id %}?html">
      {% if obj.question_img %}
        <img src="/media/{{ obj.question_img }}" height='20px'>
      {% else %}[##]{% endif %}
      </a>
    </div>
  </td>
</tr>
{% endfor %}
<table>

{% endblock content %}

django-tutorial/polls/templates/polls/pdf_test.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Polls|PDF Genrator {% endblock %}

{% block style %}
.back {
    background-color: 'red';
}
{% endblock style%}

{% block authenticated %}{% endblock %}

{% block content %}

<h2> Hi {{ user }}. Here is your auto-generated PDF </h2>
<h3> The input url was: <code>{{ url }}</code> </h3>
<p>
It includes your query strings along with a few additional
context variables added by the view and URLConf path.
</p>

<table style="border:1px solid black;" cellpadding="2">
<caption> Query Strings </caption>
{% for k, v in data.items %}
<tr><td><code>{{k}}</code></td><td>{{v}}</td>
{% endfor %}
<table>

<p>
The database contains the following Questions:
<img src="/static/img/me.jpg" height='20px'>
</p>

<table style="border:2px dashed black;" cellpadding="2">
<caption> Question Query </caption>
{% for obj in db %}
<tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ obj.question_text }}</td>
    <td>
        <div class="back">
        <img src="/media/{{ obj.question_img }}" height='20px'>
        </div>
    </td>
</tr>
{% endfor %}
<table>

<!-- display all Meta and header info on this host -->
<!-- request objects wont render into PDF -->

<table style="border:1px dotted black;" cellpadding="2">
<caption> request.headers </caption>
{% for k, v in request.headers.items %}
<tr><td><code>{{k}}</code></td><td>{{v}}</td>
{% endfor %}
</table>

<table style="border:1px dashed black;" cellpadding="2">
<caption> request.META </caption>
{% for k, v in request.META.items %}
<tr><td><code>{{k}}</code></td><td>{{v}}</td>
{% endfor %}
</table>

<hr>
{{ debug }}
<hr>

{% endblock %}

django-tutorial/polls/templates/polls/results.html
{% extends 'base.html' %}

{% block title %} Polls|Results {% endblock %}

{% block content %}

{% if not user.is_authenticated %}
  <p>You are not logged in.</p>
  <a href="{% url 'polls:login' %}">Log In Here</a>
{% else %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:pdf-detail' question.id %}">PDF?</a>

{% endif %}
{% endblock %}
!

django-tutorial/polls/templates/polls/results_bootstrap.html
{% extends 'base_bootstrap.html' %}

{% block title %} Polls|Results {% endblock %}

{% block content %}

{% if not user.is_authenticated %}
  <p>You are not logged in.</p>
  <a href="{% url 'polls:login' %}">Log In Here</a>
{% else %}

{% load pdb %}
{# {% set_breakpoint %} #}
<h1>{{ question.question_text | pdb:"off" }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<p><a href="{% url 'polls:detail' question.id %}">Vote again?</a></p>
<p><a href="{% url 'polls:pdf-detail' question.id %}">PDF?</a></p>

{% endif %}
{% endblock %}